# Generated by Django 2.2.11 on 2020-06-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200604_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
