# Generated by Django 2.2.11 on 2020-06-10 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeInformation',
        ),
        migrations.DeleteModel(
            name='UsersInformation',
        ),
    ]
